if glyph_mode == 0 {
	// Xbox 360
	glyph_action = spr_cont_xbox360_face1;
	glyph_cancel = spr_cont_xbox360_face2;
	glyph_triangle = spr_cont_xbox360_face3;
	glyph_special = spr_cont_xbox360_face4;
	glyph_select = spr_cont_xbox360_back;
	glyph_start = spr_cont_xbox360_start;
	glyph_lb = spr_cont_xbox_leftbumper;
	glyph_lt = spr_cont_xbox_lefttrigger;
	glyph_rb = spr_cont_xbox_rightbumper;
	glyph_rt = spr_cont_xbox_righttrigger;
	glyph_touchpad = "";
	glyph_l4 = "";
	glyph_r4 = "";
	glyph_l5 = "";
	glyph_r5 = "";
	glyph_func1 = "";
	glyph_func2 = "";
} else if glyph_mode == 1 {
	// Xbox One / Series X|S
	glyph_action = spr_cont_xboxone_face1;
	glyph_cancel = spr_cont_xboxone_face2;
	glyph_triangle = spr_cont_xboxone_face3;
	glyph_special = spr_cont_xboxone_face4;
	glyph_select = spr_cont_xboxone_view;
	glyph_start = spr_cont_xboxone_menu;
	glyph_lb = spr_cont_xbox_leftbumper;
	glyph_lt = spr_cont_xbox_lefttrigger;
	glyph_rb = spr_cont_xbox_rightbumper;
	glyph_rt = spr_cont_xbox_righttrigger;
	glyph_touchpad = "";
	glyph_l4 = "";
	glyph_r4 = "";
	glyph_l5 = "";
	glyph_r5 = "";
	glyph_func1 = "";
	glyph_func2 = "";
} else if glyph_mode == 3 {
	// DualShock 4
	glyph_action = spr_cont_playstation_face1;
	glyph_cancel = spr_cont_playstation_face2;
	glyph_triangle = spr_cont_playstation_face3;
	glyph_special = spr_cont_playstation_face4;
	glyph_select = spr_cont_dualshock4_share;
	glyph_start = spr_cont_dualshock4_options;
	glyph_lb = spr_cont_playstation_l1;
	glyph_lt = spr_cont_playstation_l2;
	glyph_rb = spr_cont_playstation_r1;
	glyph_rt = spr_cont_playstation_r2;
	glyph_touchpad = spr_cont_dualshock4_touchpad;
	glyph_l4 = "";
	glyph_r4 = "";
	glyph_l5 = "";
	glyph_r5 = "";
	glyph_func1 = "";
	glyph_func2 = "";
} else if glyph_mode == 6 {
	// Nintendo Switch / Switch 2 (Paired Joycons) / Switch (2) Pro Controller
	glyph_action = spr_cont_switch_face2;
	glyph_cancel = spr_cont_switch_face1;
	glyph_triangle = spr_cont_switch_face4;
	glyph_special = spr_cont_switch_face3;
	glyph_select = spr_cont_switch_minus;
	glyph_start = spr_cont_switch_plus;
	glyph_lb = spr_cont_switch_l;
	glyph_lt = spr_cont_switch_zl;
	glyph_rb = spr_cont_switch_r;
	glyph_rt = spr_cont_switch_zr;
	glyph_touchpad = "";
	glyph_l4 = "";
	glyph_r4 = "";
	glyph_l5 = "";
	glyph_r5 = "";
	glyph_func1 = "";
	glyph_func2 = "";
} else if glyph_mode == 7 {
	// Nintendo Switch / Switch 2 (Single Joycon)
	glyph_action = spr_cont_switch_face2;
	glyph_cancel = spr_cont_switch_face1;
	glyph_triangle = spr_cont_switch_face4;
	glyph_special = spr_cont_switch_face3;
	glyph_select = spr_cont_switch_minus;
	glyph_start = spr_cont_switch_plus;
	glyph_lb = spr_cont_switch_l;
	glyph_lt = spr_cont_switch_sl;
	glyph_rb = spr_cont_switch_r;
	glyph_rt = spr_cont_switch_sr;
	glyph_touchpad = "";
	glyph_l4 = "";
	glyph_r4 = "";
	glyph_l5 = "";
	glyph_r5 = "";
	glyph_func1 = "";
	glyph_func2 = "";
} else if glyph_mode == 10 {
	// DualShock 3
	glyph_action = spr_cont_playstation_face1;
	glyph_cancel = spr_cont_playstation_face2;
	glyph_triangle = spr_cont_playstation_face3;
	glyph_special = spr_cont_playstation_face4;
	glyph_select = spr_cont_dualshock3_select;
	glyph_start = spr_cont_dualshock3_start;
	glyph_lb = spr_cont_playstation_l1;
	glyph_lt = spr_cont_playstation_l2;
	glyph_rb = spr_cont_playstation_r1;
	glyph_rt = spr_cont_playstation_r2;
	glyph_touchpad = "";
	glyph_l4 = "";
	glyph_r4 = "";
	glyph_l5 = "";
	glyph_r5 = "";
	glyph_func1 = "";
	glyph_func2 = "";
} else if glyph_mode == 11 {
	// DualSense
	glyph_action = spr_cont_playstation_face1;
	glyph_cancel = spr_cont_playstation_face2;
	glyph_triangle = spr_cont_playstation_face3;
	glyph_special = spr_cont_playstation_face4;
	glyph_select = spr_cont_dualsense_create;
	glyph_start = spr_cont_dualsense_options;
	glyph_lb = spr_cont_playstation_l1;
	glyph_lt = spr_cont_playstation_l2;
	glyph_rb = spr_cont_playstation_r1;
	glyph_rt = spr_cont_playstation_r2;
	glyph_touchpad = spr_cont_dualsense_touchpad;
	glyph_l4 = "";
	glyph_r4 = "";
	glyph_l5 = "";
	glyph_r5 = "";
	glyph_func1 = spr_cont_dsedge_leftfunction;
	glyph_func2 = spr_cont_dsedge_rightfunction;
} else if glyph_mode == 12 {
	// Steam Deck / Steam Controller
	glyph_action = spr_cont_steam_face1;
	glyph_cancel = spr_cont_steam_face2;
	glyph_triangle = spr_cont_steam_face3;
	glyph_special = spr_cont_steam_face4;
	glyph_select = spr_cont_steam_view;
	glyph_start = spr_cont_steam_menu;
	glyph_lb = spr_cont_steam_l1;
	glyph_lt = spr_cont_steam_l2;
	glyph_rb = spr_cont_steam_r1;
	glyph_rt = spr_cont_steam_r2;
	glyph_touchpad = "";
	glyph_l4 = spr_cont_steam_l4;
	glyph_r4 = spr_cont_steam_r4;
	glyph_l5 = spr_cont_steam_l5;
	glyph_r5 = spr_cont_steam_r5;
}