credit_text = [
"SUNRISE",
"Creator & Director - WushR00M",
"Creator - UndergroundError",
" ",
"PROGRAMMING",
"Lead Program - WushR00M",
"Programming - TheBlueVolcano",
"Assistant Programming - SimonDoes",
"MacOS Porting - Lauren Shepard",
"Development Tools - Vadym Diachenko",
"Development Tools - Julian Adams",
"Development Tools - Alynne Keith",
"Development Tools - stoozey",
"Steamworks Development - YoYo Games",
" ",
"STORY",
"Writing - WushR00M",
"Writing - UndergroundError",
"Inspired by OneShot, by Future Cat Games",
" ",
"ART & DESIGN",
"Lead Artist - WushR00M",
"Artist - BuildZones",
"Character, Prop, and BG Art - Rose&Theo",
"Character Design - Obvlixx",
"Character Design - UndergroundError",
"Concept & Level Design - TheBlueVolcano",
"Guest Artist - Jason Lee",
" ",
"VOICE TALENT",
"Goodbye Voices:",
"- WushR00M",
"- TheBlueVolcano",
"- H4949",
"- S&WProductions (ess)",
"- XawoWasTaken",
"- Nekodex (credits to ppy and the developers of osu!)",
" ",
"MUSIC",
"Lead Musicican - WushR00M",
"Musician - Xawo_X1",
"Musician - Caystel",
"Musician - SpeheeSphereDude",
"Musician - UndergroundError",
"Guest Musician - sulflix",
"Guest Musician - Derpcat",
"Guest Musician - solare",
"Guest Musician - Soba Noodles",
"Totally Epic Music - TheFatRat",
" ",
"SOUND DESIGN",
"Sound Design - WushR00M",
"Sound Design - Xawo_X1",
"Various Sounds - Freesound",
" ",
"QA & Beta Testing",
"Design QA - Obvlixx",
"Design QA - TheBlueVolcano",
"Design QA - SimonDoes",
"Design QA - Lampshade",
"Story QA - BuildZones",
"Design & Music QA - Rose&Theo",
" ",
"SPECIAL THANKS",
"Something - collineeki",
//" ",
//"KICKSTARTER SUPPORTERS",
//"Backer - Username",
//" ", 
" ",
"© WushR00M Studios 2026",
"Sunrise: Alpha v2026.4.2",

];

scroll_y = display_get_height(); // Starts below the screen
line_height = 32;
scroll_speed = 1;

if global.creditschaptermode == true {
	audio_stop_all();
	scroll_speed = 0.9;
	audio_play_sound(mus_a_millenium_to_a_dream, 0, true, 1, 0, 0.85);
}